categories = [
    {"group_id": 1, "name": "gl_apparel"},
    {"group_id": 1, "name": "gl_jewelry"},
    {"group_id": 1, "name": "gl_shoes"},
    {"group_id": 1, "name": "gl_watch"},
    {"group_id": 2, "name": "gl_sports"},
    {"group_id": 3, "name": "gl_toy"},
    {"group_id": 5, "name": "gl_beauty"},
    {
        "group_id": 5,
        "name": "gl_home",
        "sub_categories": [
            {
                "group_id": 9,
                "name": [
                    "APPLIANCE_ACCESSORY",
                    "BAKEWARE",
                    "BATH_PILLOW",
                    "BATH_SAFETY_SEATING",
                    "BED_LINEN",
                    "BED_LINEN_SET",
                    "BED_SKIRT",
                    "BLANKET",
                    "BOTTLE",
                    "CADDY",
                    "COOKWARE",
                    "CURTAIN",
                    "CUTLERY",
                    "DECORATIVE_POM_POM",
                    "DINNERWARE",
                    "DRINKING_CUP",
                    "DUVET_COVER",
                    "FABRIC",
                    "FITTED_SHEET",
                    "FLAT_SHEET",
                    "FURNITURE_COVER",
                    "HEADBOARD",
                    "HOME_LIGHTING_AND_LAMPS",
                    "HOME_MIRROR",
                    "ITEM_STAND",
                    "JAR",
                    "KITCHEN_TOOLS",
                    "LIQUID_FUEL_CONTAINER",
                    "NAPKIN_RING",
                    "PICTURE_FRAME",
                    "PILLOW",
                    "PILLOWCASE",
                    "RUG",
                    "SERVEWARE",
                    "STORAGE_BOX",
                    "TABLECLOTH",
                    "TEMPORARY_GATE",
                    "TOWEL",
                    'BAKING_PAN',
                    'CASSEROLES',
                    'CONTAINER_LID',
                    'COOKING_POT',
                    'COOKWARE_SET',
                    'CUTTING_BOARD',
                    'HOME_BED_AND_BATH',
                    'KITCHEN_KNIFE',
                    'SAUTE_FRY_PAN',
                    'GARLIC_PRESS',
                    'DISHWARE_PLATE',
                ],
            },
            {
                "group_id": 11,
                "name": [
                    "AIR_CONDITIONER",
                    "CONTROLLER",
                    "COOKING_OVEN",
                    "HVAC_AIR_FILTER",
                    "LIGHT_BOX",
                    "LIGHT_SOURCE",
                    "VENT_HOOD",
                ],
            },
        ],
    },
    {
        "group_id": 5,
        "name": "gl_home_improvement",
        "sub_categories": [
            {"group_id": 7, "name": ["HARDWARE", "TOOLS"]},
        ],
    },
    {
        "group_id": 5,
        "name": "gl_kitchen",
        "sub_categories": [
            {
                "group_id": 7,
                "name": [
                    "COFFEE_MAKER",
                    "ELECTRIC_FAN",
                    "RICE_COOKERS",
                    "SMALL_HOME_APPLIANCES",
                    "VACUUM_CLEANER",
                ],
            },
        ],
    },
    {"group_id": 5, "name": "gl_lawn_and_garden"},
    {"group_id": 5, "name": "gl_luggage"},
    {"group_id": 5, "name": "gl_musical_instruments"},
    {
        "group_id": 5,
        "name": "gl_pet_products",
        "sub_categories": [
            {"group_id": 12, "name": "PET_FOOD"},
        ],
    },
    {"group_id": 5, "name": "gl_wireless"},
    {"group_id": 5, "name": "gl_video_games"},
    {"group_id": 6, "name": "gl_major_appliances"},
    {"group_id": 8, "name": "gl_grocery"},
    {"group_id": 9, "name": "gl_furniture"},
    {
        "group_id": 10,
        "name": "gl_drugstore",
        "sub_categories": [
            {
                "group_id": 5,
                "name": [
                    "BLOOD_PRESSURE_MONITOR",
                    "CLEANING_PRODUCT",
                    "DAILY_LIVING_AIDS",
                    "GIFT_WRAP",
                    "HAIR_CLIP",
                    "HAIR_TIE",
                    "HAIRBAND",
                    "MASSAGE_STICK",
                    "MASSAGER",
                    "MUSCLE_ROLLER",
                    "NAIL_FILE",
                    "PERSONAL_CARE_APPLIANCE",
                    "PRESCRIPTION_EYEWEAR",
                    "SEXUAL_WELLNESS",
                    "SHOE_INSERT",
                    "WIG",
                ],
            },
        ],
    },
    {"group_id": 11, "name": "gl_biss"},
    {"group_id": 11, "name": "gl_camera"},
    {"group_id": 11, "name": "gl_electronics"},
    {"group_id": 11, "name": "gl_home_entertainment"},
    {"group_id": 11, "name": "gl_office_product"},
    {
        "group_id": 11,
        "name": "gl_pc",
        "sub_categories": [
            {
                "group_id": 12,
                "name": [
                    "COMPUTER",
                    "NETWORKING_DEVICE",
                    "NOTEBOOK_COMPUTER",
                    "PERSONAL_COMPUTER",
                ],
            },
        ],
    },
    {"group_id": 11, "name": "gl_personal_care_appliances"},
    {"group_id": 14, "name": "gl_baby_product"},
    {
        "group_id": 15,
        "name": "gl_automotive",
        "sub_categories": [
            {
                "group_id": 1,
                "name": [
                    "POWERSPORTS_PROTECTIVE_GEAR",
                    "POWERSPORTS_RIDING_APPAREL",
                    "POWERSPORTS_RIDING_GLOVES",
                    "POWERSPORTS_RIDING_HELMET",
                    "POWERSPORTS_RIDING_JACKET",
                    "POWERSPORTS_RIDING_PANTS",
                    "POWERSPORTS_RIDING_SHIRT",
                    "POWERSPORTS_RIDING_SHOES",
                    "POWERSPORTS_RIDING_SUIT",
                ],
            }
        ],
    },
]
